removing dos/windows line ends and replace them with unix ones
molgenis/ConcordanceCheck pull request #18
Opened 2021-08-25 09:17 UTC by RoanKanninga

2021-08-25 14:59 UTC, pneerincx commented on bin/ParseDarwinSamplesheet.sh
> +		cat ${darwinSamplesheet} | sed 's/\r/\n/g' | sed "/^[\s,]*$/d" > "${darwinSamplesheet}.converted"
Missing quotes for `${darwinSamplesheet}` -> `"${darwinSamplesheet"`

2021-08-25 14:59 UTC, pneerincx requested changes
See inline comment.

2021-08-26 05:05 UTC, RoanKanninga commented on bin/ParseDarwinSamplesheet.sh
> +		cat ${darwinSamplesheet} | sed 's/\r/\n/g' | sed "/^[\s,]*$/d" > "${darwinSamplesheet}.converted"
check, fixed

2021-08-26 06:22 UTC, pneerincx submitted a review, later dismissed

2021-10-06 10:01 UTC, marieke-bijlsma commented on README.md
> +   ⎜ LFS  ⎜ Copies the nsg VCF and the array VCF file to tmp*.                                       ⎜
```suggestion
   ⎜ LFS  ⎜ Copies the ngs VCF and the array VCF file to tmp*.                                       ⎜
```

2021-10-06 10:07 UTC, marieke-bijlsma submitted a review, later dismissed

2021-10-06 10:35 UTC, marieke-bijlsma approved these changes

2021-10-06 10:35 UTC, merged